### PR TITLE
Forbid starting stream when it's suspended or deleted

### PR DESCRIPTION
**Pull request by leszko**
fix https://linear.app/livepeer/issue/PS-227/qiang-we-are-testing-new-camera-firmware-and-observing-strange-issue

### CODE REVIEW

**Comment by thomshutt** [comment]
@leszko I'd tried to do this in https://github.com/livepeer/catalyst-api/pull/1133 - should we get rid of that?

**Comment by leszko** [comment]
> @leszko I'd tried to do this in #1133 - should we get rid of that / any idea why it's not working here?

Not sure TBH. What was the purpose of your change? When I tried in the box, even without your change and my change, I couldn't play the pull stream when it was suspended.

**Comment by thomshutt** [comment]
@leszko my change was to stop terminated Pull streams coming back to life when a new viewer initiated a playback

**Comment by leszko** [comment]
> @leszko my change was to stop terminated Pull streams coming back to life when a new viewer initiated a playback

Hmm, I tried in the box, and even without your change, a new playback didn't work after the stream was suspended... 🤔

**Comment by thomshutt** [comment]
I think we probably need both though - yours covers the autopush and mine covers new viewers

**Comment by leszko** [comment]
> I think we probably need both though - yours covers the autopush and mine covers new viewers

Yeah, that's what I think as well. One is ingest, one is watching.

**Review by thomshutt — APPROVED** [review]

**Pull request merged**
