### PR TITLE
handlers: exit if a bad request or error is encountered

### PR DESCRIPTION
**Pull request by emranemran**

### CODE REVIEW

**Review by red-0ne — COMMENTED** [review]
There is a missing one here https://github.com/livepeer/catalyst-api/blob/10dd863d55e1148e5505e079e4d22b0e809a336b/handlers/upload.go#L147

```
if err := clients.DefaultCallbackClient.SendTranscodeStatus(uploadVODRequest.CallbackUrl, clients.TranscodeStatusPreparing, 0.0); err != nil {
	errors.WriteHTTPInternalServerError(w, "Cannot send transcode status", err)
}
```

**Comment by emranemran** [comment]
> There is a missing one here
> 
> https://github.com/livepeer/catalyst-api/blob/10dd863d55e1148e5505e079e4d22b0e809a336b/handlers/upload.go#L147
> 
> ```
> if err := clients.DefaultCallbackClient.SendTranscodeStatus(uploadVODRequest.CallbackUrl, clients.TranscodeStatusPreparing, 0.0); err != nil {
> 	errors.WriteHTTPInternalServerError(w, "Cannot send transcode status", err)
> }
> ```

@red-0ne I left that one out on purpose. That's the callback to studio so it didn't make sense to bail early if it happens to fail to notify studio - we should continue with everything anyways.

**Review by thomshutt — APPROVED** [review]

**Comment by thomshutt** [comment]
LGTM, good job catching this @red-0ne!

**Comment by red-0ne** [comment]
> > There is a missing one here
> > https://github.com/livepeer/catalyst-api/blob/10dd863d55e1148e5505e079e4d22b0e809a336b/handlers/upload.go#L147
> > 
> > ```
> > if err := clients.DefaultCallbackClient.SendTranscodeStatus(uploadVODRequest.CallbackUrl, clients.TranscodeStatusPreparing, 0.0); err != nil {
> > 	errors.WriteHTTPInternalServerError(w, "Cannot send transcode status", err)
> > }
> > ```
> 
> @red-0ne I left that one out on purpose. That's the callback to studio so it didn't make sense to bail early if it happens to fail to notify studio - we should continue with everything anyways.

You are right. Thanks for the clarification. Shouldn't we have this in a goroutine to save up some transcoding time then?

**Comment by red-0ne** [comment]
Also, we shouldn't write the error to the response then proceed to write response bytes coming out of transcoding. IMHO we should not do anything with responses from `SendTranscodeStatus`.

**Comment by thomshutt** [comment]
I think you're right on both counts @red-0ne - feel free to put in a followup PR to fix. I think the goroutine should be spawned intside the callback client and then it should just log and not return anything on errors

**Comment by red-0ne** [comment]
> I think you're right on both counts @red-0ne - feel free to put in a followup PR to fix. I think the goroutine should be spawned intside the callback client and then it should just log and not return anything on errors

I've worked on this followup and it seems that it is easier to have the goroutine outside of the callback if we want to keep testing errors of the sendTranscodeStatus request without adding some mechanism to capture the error from outside. Otherwise we be removing 4 assertions from 2 tests of the callback client. WDYT?

**Pull request merged**
