### PR TITLE
Reduce the number of goroutines for the directory copy

### PR DESCRIPTION
**Pull request by mjh1**
We have been seeing a lot of connection reset errors when copying the output files, trying a lower number of goroutines to see if it improves the situation since 10 per job seemed a lot. I tested with different numbers of goroutines, even just a single routine and it didn't seem to have a big impact on the time to copy.

### CODE REVIEW

**Comment by mjh1** [comment]
@emranemran Just realised that a fix went in from @leszko for the retry mechanism used here, so perhaps this PR is not necessary. What do you guys think, should I just mark this as draft until we see what https://github.com/livepeer/catalyst-api/pull/478 effect has?

**Comment by leszko** [comment]
> @emranemran Just realised that a fix went in from @leszko for the retry mechanism used here, so perhaps this PR is not necessary. What do you guys think, should I just mark this as draft until we see what https://github.com/livepeer/catalyst-api/pull/478 effect has?

I think you're right. We can keep it as a draft and see if it's needed.

**Comment by thomshutt** [comment]
Shall we close this?

**Comment by mjh1** [comment]
Yep 👍

**Pull request closed without merging**
